apiVersion: v1
kind: Pod
metadata:
  name: primeiro-pod
  labels:
    name: primeiro-pod
spec:
  containers:
  - name: container1
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 9000
