image: docker:stable

stages:
- pre-build
- build
- test
- deploy 
- notificacao

#############################
build-docker:
  services:
  - docker:dind
  retry: 2
  before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

  stage: pre-build
  script:
  - docker build -t gitlab-alura .
  - docker tag gitlab-alura alexgwasp/gitlab-alura:latest
  - docker push alexgwasp/gitlab-alura:latest

#############################
build-project:
  image: alexgwasp/gitlab-alura:latest
  services:
  - docker:dind
  - mysql:5.7

  variables:
    MYSQL_USER: $DB_USER 
    MYSQL_PASSWORD: $DB_PASSWORD 
    MYSQL_DATABASE: $DB_DATABASE 
    MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD 

    DB_USER: $DB_USER
    DB_PASSWORD: $DB_PASSWORD
    DB_NAME: $DB_DATABASE
    DB_PORT: '3306'
    DB_HOST: 'mysql'
    SECRET_KEY: $DB_SECRET_KEY
  
  stage: build
  dependencies:
  - build-docker
  tags:
  - agent
  script:
  - python manage.py makemigrations
  - python manage.py migrate

#############################
test-project:
  image: alexgwasp/gitlab-alura:latest
  services:
  - docker:dind
  - mysql:5.7

  variables:
    MYSQL_USER: $DB_USER 
    MYSQL_PASSWORD: $DB_PASSWORD 
    MYSQL_DATABASE: $DB_DATABASE 
    MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD 

    DB_USER: $DB_USER
    DB_PASSWORD: $DB_PASSWORD
    DB_NAME: $DB_DATABASE
    DB_PORT: '3306'
    DB_HOST: 'mysql'
    SECRET_KEY: $DB_SECRET_KEY

  stage: test
  dependencies:
  - build-project
  tags:
  - agent
  script:
  - python -m unittest setUp

#############################
deploy-project:
  stage: deploy
  tags:
  - executor-deploy
  dependencies:
  - test-project
  script:
  - tar cfz arquivos.tgz * 
  - scp arquivos.tgz aluraverde@192.168.1.34:/Users/Shared/deploy/
  - ssh aluraverde@192.168.1.34 ' cd /Users/Shared/deploy/; tar xfz arquivos.tgz; /usr/local/bin/docker-compose up -d'

#############################
notificacao-sucesso:
  stage: notificacao
  tags:
  - executor-deploy
  when: on_success
  script:
  - sh notificacaoSucesso.sh 

#############################
notificacao-falhas:
  stage: notificacao
  tags:
  - executor-deploy
  when: on_failure
  script:
  - echo sh notificacaoFalha.sh
