apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: pod-1
  ports:
    - port: 80
      nodePort: 30000 # Poder ser entre 30000 a 32767
      # para acesso do serviço no windows executar no navegador: localhost:30000
      # para acesso no Linux executar:f
      # "kubectl get nodes -o wide" e pegar o IP interno do minikube
      # ir no browser e executar <IP>:30000
